# Generated by Django 2.2.5 on 2019-09-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='toppings1',
            new_name='topping1',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='toppings2',
            new_name='topping2',
        ),
    ]
